terraform-aws-modules/terraform-aws-route53

examples/complete/main.tf, modules/zones/README.md, modules/zones/main.tf, modules/zones/variables.tf
Taken from https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_zone#private-zone
This PR allows you to add a `vpc_block` to specify which AWS vpc you want to attach this route53 zone to and create a private hosted zone
This PR allows you to create a private hosted zone(s)
No breaking changes, adding new functionality.
- Tested by creating one / many private hosted zones
- Tested previous functionality by created one / many public hosted zones
- Caution: A limitation of Terraform ("all map elements must have the same type") does not allow you to create a mix of private/public zones in a single `zones` variable.
=> feat: Adding dynamic vpc block to handle private zones

examples/complete/main.tf, modules/records/main.tf
Call to `object()` as a function is not available, use `tomap()`
The ternary expression for records creation contains a call to `object()` which is not available as a function.
To get the same grasp on enforcing type I did use `tomap()` instead of a literal only.
```sh
Error: Call to unknown function
on .terraform/modules/vault_cluster.dns/modules/records/main.tf line 15, in resource "aws_route53_record" "this":
15:   for_each = var.create && (var.zone_id != null || var.zone_name != null) ? local.recordsets : object({})
There is no function named "object".
```
None
Terraform (0.12) plan and apply on AWS resources with a `create` input variable set to `false`
```hcl
module "dns" {
source  = "terraform-aws-modules/route53/aws//modules/records"
version = "~> 1.2.0"
zone_id = …
```
=> fix: use tomap() instead of type declaration object()

README.md, examples/complete/main.tf, modules/zones/README.md, modules/zones/main.tf, modules/zones/variables.tf
Add a global `tags` variable for tags that should be added to all Route53 zones.
Tags like `ManagedBy = "Terraform"` and similar should only be set once as this will make it much easier to manage.
Zones have been created with and without tags.
=> feat: add global tags variable to zones

examples/complete/main.tf, examples/complete/outputs.tf, modules/zones/main.tf, modules/zones/outputs.tf
Currently the `zones` module only supports a single VPC. The `aws_route53_zone` resource supports multiple VPCs for private zones so I'm adding support for that.
I needed a private hosted zone with multiple VPCs. This module didn't support it, now it does.
Yes, we are changing `vpc` attribute from a `map` to a `list(map)` so if anyone us using a map, they'll need to wrap with `[{..}]`
I just used it to create a private hosted zone for what I needed.
```HCL
locals {}
terraform {
source = "/Users/hnicholas/.local/tmp/terraform-aws-route53/modules/zones"
}
include {
path = find_in_parent_folders()
}
dependency "us_gov_east_1_vpc" {
config_path = "../../../us-gov-east-1/apps/vpc"
}
dependency "us_gov_west_1_vpc" {
config_path = "../../../us-gov-west-1/apps/vpc"
}
inputs = {
zones = { …
```
=> feat: Add support for multiple VPCs when creating private hosted zones

.gitignore, .pre-commit-config.yaml, README.md, examples/complete/README.md, modules/records/README.md, modules/zones/README.md
- update documentation based on latest `terraform-docs` which includes module and resource sections
- `.gitignore` updated using GitHub provided default standard + 0.14 lockfile ignore
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)
No
N/A
=> chore: update documentation based on latest `terraform-docs` which includes module and resource sections

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, examples/complete/README.md, examples/complete/versions.tf, modules/records/README.md, modules/records/versions.tf, modules/zones/README.md, modules/zones/versions.tf
- correct documentation based on update by `terraform_docs`
- bump min supported version due to types unsupported on current
- static checks are currently failing due to docs mis-match
- No
- static checks
=> fix: correct documentation based on update by `terraform_docs`

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, examples/complete/README.md, modules/records/README.md, modules/zones/README.md
- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks
=> chore: update documentation and pin `terraform_docs` version to avoid future changes

examples/complete/main.tf, modules/records/main.tf
With this change users can create aliasses for the same zone as for which the records are being created.
It allows for existing users to keep on using the module without breaking.
If you don't supply a zone_id for your alias record, it now defaults to the zone_id of the zone for which the entry is being created. 
Example of list of records being created by a looped call of the records module:
`{ name = "www.test", type = "A", ttl = null, alias = { name = "test.mydomain.com" } },`
previously this would result in a error since the zone_id in the alias object isn't specified while being required.
In other words this:
`{ name = "www.test", type = "A", ttl = null, alias = { name = "test.mydomain.com" , zone_id = "<id>"} },`
would be allowed while this:
`{ name = "www.test", type = "A", ttl = …
=> feat: Add ability for users to create aliases in the same zone

examples/complete/main.tf, modules/records/main.tf
Supported geolocation routing policy and multivalue answer routing policy in records module.
I'm adding these policies because AWS supports them and I use them. The module doesn't support them before the change.
None
My deployments
=> feat: Add geo routing policy and multivalue answer routing policy

.pre-commit-config.yaml, examples/complete/README.md, examples/complete/main.tf, examples/complete/versions.tf, modules/records/README.md, modules/records/versions.tf, modules/zones/README.md, modules/zones/versions.tf
Support dual-stack (IPv4 and IPv6) access to the distribution
This example provided only IPv4
none known
I employed these changes in my own distribution
=> chore: Updated example with AAAA records for dual-stack CloudFront

README.md, examples/complete/README.md, examples/complete/main.tf, examples/complete/outputs.tf, modules/delegation-sets/README.md, modules/delegation-sets/main.tf, modules/delegation-sets/outputs.tf, modules/delegation-sets/variables.tf, modules/delegation-sets/versions.tf, modules/zones/main.tf
Add delegation_sets module for creating delegation sets. The implementation (logic, variables and outputs) is similar to the implementation of the zones module.
A delegation set id may be specified in the parameters of a public zone to have that zone use the set of name servers from the delegation set.
Update the example to create and use a delegation set.
By supporting the creation and use of delegation sets, multiple public zones can use the same set of name servers. May be useful when doing batch updates of name servers at other registrars.
It shouldn't break anything, new functionality is added.
Tested by deploying the example.
=> feat: Added support for delegation sets

.pre-commit-config.yaml, examples/complete/README.md, examples/complete/main.tf, modules/records/README.md, modules/records/main.tf, modules/records/variables.tf
…efix to the record name
add full_override_name override to disable adding domain name as a prefix to the record name
add possibility to read the exported dns file taht contains full names.
=> feat: Added full_override_name override to disable adding domain name to record names

README.md, examples/complete/README.md, examples/complete/main.tf, examples/complete/outputs.tf, modules/resolver-rule-associations/README.md, modules/resolver-rule-associations/main.tf, modules/resolver-rule-associations/outputs.tf, modules/resolver-rule-associations/variables.tf, modules/resolver-rule-associations/versions.tf
Resolver rule association module was added
It is used to create one or more resolver rule associations
Clear addition
- tflint
- terraform fmt
- real resolver rule associations created
=> feat: Add resolver rule association module

examples/complete/README.md, examples/complete/main.tf, examples/complete/outputs.tf, modules/records/README.md, modules/records/main.tf, modules/records/variables.tf, terragrunt_59.md
~It is still not working, and after wasting more than 20 hours on fixing #59 ... I give up (for now)...~
~If anyone likes challenges, please try to finish this PR.~
~All information and "definition of done" is [modules/records/main.tf](https://github.com/terraform-aws-modules/terraform-aws-route53/pull/72/files#diff-15c488fdc1301bb287fd6b94ed88c499fba27aeb9615824838ce468e96dc11a0).~
Huge thanks to @flora-five for figuring out the working solution.
Fixes #59
=> fix: Fixed the for_each value depends on resource attributes that cannot be determined until apply

examples/complete/main.tf, modules/records/main.tf
It will add support for latency routing policies for `records` module
Useful when having resources in multiple AWS Regions and you want to route traffic to the region that provides the best latency. You can use latency routing to create records in a private hosted zone too.
The feature is already supported by the resource.
It closes #75
=> feat(records): Add support for latency routing policy

examples/complete/README.md, examples/complete/outputs.tf, modules/zones/README.md, modules/zones/outputs.tf
Add the route53 zone ARN to outputs.
ARN is needed in other modules.
No
=> feat: Add zone ARN to outputs

examples/complete/README.md, examples/complete/outputs.tf, examples/complete/versions.tf, modules/delegation-sets/versions.tf, modules/records/versions.tf, modules/resolver-rule-associations/versions.tf, modules/zones/README.md, modules/zones/outputs.tf, modules/zones/versions.tf
Added static zone name output that is useful when creating zones and records simultaneously (as described in #101).
Fixes #101
=> feat: Added static zone name output

.github/workflows/lock.yml, .github/workflows/pr-title.yml, .github/workflows/pre-commit.yml, .github/workflows/release.yml, .github/workflows/stale-actions.yaml, .pre-commit-config.yaml, examples/complete/README.md, examples/complete/main.tf, examples/complete/versions.tf
- Update CI workflow versions to remove deprecated runtime warnings
- Updates our workflows to use the latest versions
- Removes the `deprecated runtime` warnings from the workflow execution output
- No
=> fix: Update CI workflow versions to remove deprecated runtime warnings

.pre-commit-config.yaml, README.md, examples/complete/README.md, examples/complete/main.tf, examples/complete/versions.tf, modules/delegation-sets/README.md, modules/delegation-sets/versions.tf, modules/records/README.md, modules/records/main.tf, modules/records/versions.tf, modules/resolver-rule-associations/README.md, modules/resolver-rule-associations/versions.tf, modules/zones/README.md, modules/zones/versions.tf
This change extends the route53 records module by adding support for geoproximity routing policy.
AWS recently added support for [geopriximity](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy-geoproximity.html) routing and this change will allow creation of records using that new policy. The module currently does not support it.
=> feat!: Add support for geoproximity routing policy. Upgraded TF version to 1.3.2

README.md, examples/complete/README.md, examples/complete/main.tf, modules/resolver-endpoints/README.md, modules/resolver-endpoints/main.tf, modules/resolver-endpoints/outputs.tf, modules/resolver-endpoints/variables.tf, modules/resolver-endpoints/versions.tf
This PR add a new submodule to create Route53 Resolver Endpoints
Through Resolver endpoints and conditional forwarding rules, you can resolve DNS queries between your on-premises resources and VPCs to create a hybrid cloud setup over VPN or Direct Connect (DX). Specifically:
- Inbound Resolver endpoints allow DNS queries to your VPC from your on-premises network or another VPC.
- Outbound Resolver endpoints allow DNS queries from your VPC to your on-premises network or another VPC.
N/A
=> feat: Add resolver-endpoints submodule

examples/complete/main.tf, modules/zones/README.md, modules/zones/outputs.tf, modules/zones/versions.tf
One more output has been added in zones module in this PR: `primary_name_server`.
This new output could be useful if SOA record modification is required in dependent modules.
No breaking changes
=> feat!: Add primary name server to outputs in modules/zones. Bump AWS provider version to 4

examples/complete/README.md, examples/complete/main.tf, modules/resolver-endpoints/README.md, modules/resolver-endpoints/main.tf, modules/resolver-endpoints/variables.tf
This PR complements https://github.com/terraform-aws-modules/terraform-aws-route53/pull/106 by adding a new variable, allowing the submodule to update egress rules. This PR also adds support for setting static IP address on the resolver endpoint instances.
The previous pull request was hardcoding an egress rule allowing All the traffic. Users could want to update these rules as their needs.
=> fix: Add egress rule update support

.pre-commit-config.yaml, README.md, examples/complete/README.md, examples/complete/main.tf, modules/delegation-sets/README.md, modules/delegation-sets/main.tf, modules/records/README.md, modules/resolver-endpoints/README.md, modules/resolver-endpoints/main.tf, modules/resolver-rule-associations/README.md, modules/zone-cross-account-vpc-association/README.md, modules/zone-cross-account-vpc-association/main.tf, modules/zone-cross-account-vpc-association/outputs.tf, modules/zone-cross-account-vpc-association/variables.tf, modules/zone-cross-account-vpc-association/versions.tf, modules/zones/README.md
This PR add a new submodule to create cross-account Route53 VPC associations, using the authorization association resources (https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zone-private-associate-vpcs-different-accounts.html)
For cross-account AWS documentation generally recommends using Route53Resolver. The API endpoint [CreateVPCAssociationAuthorization](https://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateVPCAssociationAuthorization.html) is not even implemented in AWS Console.
However, this option is simpler as it does not require explicit resolver infrastructure (living within the VPC with specific Elastic Network Interfaces) and it does not involve cost on paying the Route53Resolver infrastructure, which makes it ideal for (most) cases.
N/A
>
=> feat: Add zone-cross-account-vpc-association submodule

examples/complete/main.tf
Added an example of an MX record
I wanted to add an MX record and there was no previous example or notation of this option.
None
Local lint testing
Terraform plan and tf apply
Confirmed with visual confirmation in the console.
=> chore: Added MX records in the example code

.github/workflows/pr-title.yml, .github/workflows/pre-commit.yml, .pre-commit-config.yaml, modules/zone-cross-account-vpc-association/README.md
- Update CI workflow versions to latest
- Updates our workflows to use the latest versions
- Removes warnings for Python 3.12 in runners
- No
=> fix: Update CI workflow versions to latest

examples/complete/README.md, examples/complete/main.tf, examples/complete/versions.tf, modules/delegation-sets/README.md, modules/delegation-sets/versions.tf, modules/records/README.md, modules/records/main.tf, modules/records/versions.tf, modules/resolver-endpoints/README.md, modules/resolver-endpoints/versions.tf, modules/resolver-rule-associations/README.md, modules/resolver-rule-associations/versions.tf, modules/zone-cross-account-vpc-association/README.md, modules/zone-cross-account-vpc-association/versions.tf, modules/zones/README.md, modules/zones/main.tf, modules/zones/versions.tf
Support timeouts for zones and records. 
Support CIDR routing policy for records. 
MSV AWS v5. 
- https://github.com/hashicorp/terraform-provider-aws/issues/41741
- https://github.com/hashicorp/terraform-provider-aws/pull/29407
Yes. MSV AWS v5.
=> feat!: Support timeouts, `cidr_routing_policy`, MSV of AWS provider v5
